@startuml

title プロセスフロー図

' 要素一覧
usecase プロセス
usecase/ 階層化されたプロセス
agent "成果物(単票)"
collections "成果物(副票)"
cloud 無形成果物


agent 経営計画
cloud マネジメント要求
usecase プロジェクト要求を抽出する
agent 6R
usecase プロジェクトを定義する
agent プロジェクトチャーター
usecase/ 要件を定義する
collections 要求仕様書


' フロー
経営計画 --> プロジェクト要求を抽出する
マネジメント要求 --> プロジェクト要求を抽出する
プロジェクト要求を抽出する --> 6R
6R --> プロジェクトを定義する
プロジェクトを定義する --> プロジェクトチャーター
プロジェクトチャーター --> 要件を定義する
6R --> 要件を定義する
要件を定義する --> 要求仕様書


@enduml


