@startuml

package framework {
  class Factory
  class Product
}

package idcard {
  class IDCardFactory
  class IDCard
}

class Factory {
  create()
  createProduct()
  registerProduct()
}

class Product {
  use()
}

class IDCardFactory {
  owenrs
  createProduct()
  registerProduct()
  getOwners()
}

class IDCard {
  owner
  use()
  getOwner()
}


Factory --> Product : Creates >
IDCardFactory --|> Factory
IDCardFactory --> IDCard : Creates >
IDCard --|> Product



@enduml