@startuml

package framework {
  class Factory
  class Product
}

package concrete {
  class concreteFactory
  class concreteProduct
}

class Factory {
  create()
  createProduct()
}

class Product {
  method()
}

class concreteFactory {
  createProduct()
}

class concreteProduct {
  method()
}


Factory --> Product : Creates >
concreteFactory --> concreteProduct : Creates >
concreteFactory --|> Factory
concreteProduct --|> Product



@enduml